Repository OI-wiki/OI-wiki, pull requests merged in 2018-10, with the labels that each got.

#449 Update cdq-divide.md
  docs/misc/cdq-divide.md
Labels: 格式需修正 / Format fix needed

#566 加入有关运算符优先级相关的内容
  docs/math/bit.md
Labels: good first issue

#588 错别字修正
  docs/graph/topo.md
Labels: good first issue

#591 重新写了一发cdq分治
  docs/misc/cdq-divide.md
  docs/misc/images/cdq1.png
Labels: 备忘 / backlog, 需要讨论 / discussion
