Repository OI-wiki/OI-wiki, pull requests merged in 2018-08, with the labels that each got.

#40 add more details
  README.md
  build.sh
  docs/graph/bi-graph.md
  docs/graph/dag.md
  docs/graph/images/bi-graph.png
  docs/graph/topo.md
  docs/graph/tree-basic.md
  docs/math/gauss.md
  docs/math/images/gauss1.png
  docs/math/images/gauss10.png
  docs/math/images/gauss11.png
  docs/math/images/gauss12.png
  docs/math/images/gauss13.png
  docs/math/images/gauss2.png
  docs/math/images/gauss3.png
  docs/math/images/gauss4.png
  docs/math/images/gauss5.png
  docs/math/images/gauss6.png
  docs/math/images/gauss7.png
  docs/math/images/gauss8.png
  docs/math/images/gauss9.png
  docs/math/images/picture
  mkdocs.yml
Labels: review

#41 Update gauss.md
  docs/math/gauss.md
Labels: review

#43 Update combination.md
  docs/math/combination.md
Labels: review

#44 Update combination.md
  docs/math/combination.md
Labels: review

#45 Update combination.md
  docs/math/combination.md
Labels: review

#46 Update combination.md
  docs/math/combination.md
Labels: review

#47 Update combination.md
  docs/math/combination.md
Labels: review

#48 Update combination.md
  docs/math/combination.md
Labels: review

#49 Update combination.md
  docs/math/combination.md
Labels: review

#50 Update combination.md
  docs/math/combination.md
Labels: review

#52 add sa, and some minor fix
  .travis.yml
  docs/string/images/sa1.png
  docs/string/images/sa2.png
  docs/string/images/sa3.png
  docs/string/sa.md
  mkdocs.yml
Labels: review

#54 fix: fix wrong image links
  docs/string/sa.md
Labels: review

#55 multiple fix
  .gitkeep
  docs/basic/images/.gitkeep
  docs/data-structure/advanced/images/.gitkeep
  docs/data-structure/images/.gitkeep
  docs/data-structure/novice/images/.gitkeep
  docs/dp/images/.gitkeep
  docs/dp/memo.md
  docs/geometry/images/.gitkeep
  docs/graph/flow/images/.gitkeep
  docs/images/.gitkeep
  docs/introduction/images/.gitkeep
  docs/misc/images/.gitkeep
  docs/search/images/.gitkeep
  docs/string/sa.md
  mkdocs.yml
Labels: review

#56 Update combination.md
  docs/math/combination.md
Labels: review

#57 fix: fixed some formulas
  docs/math/combination.md
  docs/math/gauss.md
  docs/math/images/gauss1.png
  docs/math/images/gauss10.png
  docs/math/images/gauss11.png
  docs/math/images/gauss12.png
  docs/math/images/gauss13.png
  docs/math/images/gauss2.png
  docs/math/images/gauss3.png
  docs/math/images/gauss4.png
  docs/math/images/gauss5.png
  docs/math/images/gauss6.png
  docs/math/images/gauss7.png
  docs/math/images/gauss8.png
  docs/math/images/gauss9.png
Labels: good first issue, review

#58 feat: add progress bar, change doc
  README.md
  docs/math/catalan.md
  docs/math/combination.md
  docs/math/stirling.md
  mkdocs.yml
  requirements.txt
Labels: review

#60 Update combination.md
  docs/math/combination.md
Labels: review

#61 fix: get the images folder back
  docs/math/images/.gitkeep
  docs/math/images/容斥原理1.png
  mkdocs.yml
  requirements.txt
Labels: review

#65 multiple update
  README.md
  build.sh
  docs/data-structure/intermediate/bit.md
  docs/data-structure/intermediate/segment.md
  docs/data-structure/novice/heap.md
  docs/data-structure/novice/square-root-decomposition.md
  docs/graph/basic.md
  docs/graph/bcc.md
  docs/graph/dag.md
  docs/graph/mst.md
  docs/graph/scc.md
  docs/graph/shortest-path.md
  docs/graph/traverse.md
  docs/index.md
  docs/math/bsgs.md
  docs/math/divide.md
  docs/math/divisor.md
  docs/math/euclid.md
  docs/math/gcd.md
  docs/math/numeral-calculations.md
  docs/string/ac-automaton.md
  docs/string/hash.md
  docs/string/index.md
  docs/string/kmp.md
  docs/string/match.md
  docs/string/stl.md
  docs/string/trie.md
  mkdocs.yml
  requirements.txt
Labels: review

#66 minor fix on styles, settings and 404
  README.md
  build.sh
  docs/index.md
  mkdocs.yml
Labels: review

#72 minor fix
  docs/data-structure/novice/dsu.md
  static/disqus.html
Labels: review

#73 fix: fix gitment for pages without title
  static/disqus.html
Labels: review

#74 fix: fix gitment
  static/disqus.html
Labels: review

#77 Add files via upload
  docs/data-structure/advanced/seg-in-seg.md
Labels: review

#78 update commenting systems
  static/disqus.html
Labels: review

#81 add more docs and fix gitmint
  .github/CONTRIBUTING.md
  README.md
  static/disqus.html
Labels: review

#82 fix formulas and code highlights
  docs/data-structure/advanced/seg-in-seg.md
Labels: review

#84 minor fix on docs
  .github/CONTRIBUTING.md
  README.md
Labels: review

#80 Update hash.md
  docs/string/hash.md
Labels: good first issue

#87 Update hash.md
  docs/string/hash.md
Labels: good first issue

#88 feat: update treap
  docs/data-structure/advanced/seg-in-seg.md
  docs/data-structure/intermediate/treap.md
Labels: review

#89 style: fix formula style (gcd -> \gcd)
  docs/math/fermat.md
Labels: review

#92 multiple update
  docs/data-structure/intermediate/treap.md
  docs/graph/lca.md
  docs/graph/topo.md
  docs/graph/tree-misc.md
  docs/math/complex.md
  docs/math/crt.md
  docs/math/fft.md
  docs/math/fwt.md
  docs/math/ntt.md
  docs/math/prime.md
  docs/search/bfs.md
  docs/string/kmp.md
  mkdocs.yml
Labels: review

#94 minor fix
  .github/CONTRIBUTING.md
  docs/introduction/faq.md
  docs/misc/matrix-tree.md
Labels: review

#95 feat: add balanced-in-seg.md
  docs/data-structure/advanced/balanced-in-seg.md
Labels: review

#96 style: updata style
  docs/data-structure/advanced/seg-in-seg.md
Labels: review

#97 minor update
  docs/introduction/faq.md
  docs/math/bignum.md
  mkdocs.yml
Labels: review

#101 LCA and segment update
  docs/data-structure/intermediate/segment.md
  docs/graph/lca.md
Labels: review

#106 merge .github/CONTRIBUTING.md into faq.md
  docs/introduction/faq.md
Labels: review

#109 Update drawer-principle.md
  docs/math/drawer-principle.md
Labels: review

#118 Minor fix and cleanup
  docs/misc/inandout.md
  docs/miscinandout.md
Labels: review

#119 Ir1d patch 2
  docs/misc/io.md
  mkdocs.yml
Labels: review

#113 change shift symbol in bit.md
  docs/math/bit.md
Labels: review

#122 add meta description for index page
  docs/index.md
Labels: review

#123 modify title of index page
  docs/index.md
  mkdocs.yml
Labels: review

#126 Correct the format
  docs/geometry/2d.md
Labels: review

#128 Update mkdocs.yml
  mkdocs.yml
Labels: review

#129 Update basic.md
  docs/graph/basic.md
Labels: review

#131 arrange formula
  docs/math/gcd.md
  docs/math/ntt.md
  docs/math/prime.md
Labels: review

#132 Update mkdocs.yml
  mkdocs.yml
Labels: review

#134 Add math/dictionary and correct a mistake
  docs/geometry/2d.md
  docs/math/dictionary.md
Labels: review

#135 fix math display
  docs/math/combination.md
Labels: review

#137 Update combination.md
  docs/math/combination.md
Labels: review

#138 math display fix for combination
  docs/basic/sort.md
  docs/math/combination.md
Labels: review

#139 Update backpack.md
  docs/dp/backpack.md
Labels: review

#136 Update state.md
  docs/dp/state.md
Labels: review

#141 Add Online Judging System: Virtual Judge
  docs/introduction/resources.md
Labels: review

#143 fix: typo; writing
  docs/data-structure/novice/dsu.md
Labels: review

#145 fix typo
  docs/introduction/resources.md
Labels: review

#146 Update resources.md
  docs/introduction/resources.md
Labels: review

#147 change domain, update progress and minor fix on style
  README.md
  docs/CNAME
  docs/data-structure/advanced/balanced-in-seg.md
  docs/dp/backpack.md
  docs/geometry/2d.md
  docs/introduction/faq.md
  docs/math/complex.md
  docs/math/dictionary.md
  mkdocs.yml
Labels: review

#149 Update complex.md
  docs/math/complex.md
Labels: review

#150 minor update
  README.md
  deploy.sh
  static/robots.txt
Labels: review

#151 fix: fix static file
  deploy.sh
  docs/robots.txt
Labels: review

#152 fix: fix comments
  static/disqus.html
Labels: review

#142 Update monotonous-queue.md
  docs/data-structure/novice/monotonous-queue.md
Labels: review

#153 update style and udpate bfs
  docs/graph/traverse.md
  docs/introduction/faq.md
  docs/search/bfs.md
  docs/string/sa.md
Labels: review

#156 Fix minor style issue
  docs/math/prime.md
Labels: review

#154 Fix Latex Formula
  docs/misc/mo-algo.md
Labels: review

#157 Add complexity
  docs/misc/complexity.md
  docs/misc/images/order.png
Labels: review

#158 Fix style issue
  docs/misc/complexity.md
Labels: review

#164 multiple update.
  .github/CONTRIBUTING.md
  docs/basic/divide-and-conquer.md
  docs/basic/sort.md
  docs/data-structure/novice/linked-list.md
  docs/data-structure/novice/queue.md
  docs/data-structure/novice/stack.md
  docs/introduction/faq.md
  docs/misc/discrete.md
  docs/search/bfs.md
  mkdocs.yml
Labels: review

#166 feat: enable Google Analytics
  docs/_static/js/extra.js
  mkdocs.yml
Labels: review

#167 Update extra.js
  docs/_static/js/extra.js
Labels: review

#165 Add SAM, Equation Rendering Improvements & Readme Typos. Fix
  README.md
  docs/_static/js/extra.js
  docs/string/images/SAM/SA.pdf.svg
  docs/string/images/SAM/SA_suffix_links.pdf.svg
  docs/string/images/SAM/SAa.pdf.svg
  docs/string/images/SAM/SAaa.pdf.svg
  docs/string/images/SAM/SAab.pdf.svg
  docs/string/images/SAM/SAaba.pdf.svg
  docs/string/images/SAM/SAabb.pdf.svg
  docs/string/images/SAM/SAabbb.pdf.svg
  docs/string/sam.md
Labels: review

#169 feat: enable words counting and LICENSE statement inside pages
  .github/CONTRIBUTING.md
  build.sh
  docs/_static/css/extra.css
  docs/_static/js/extra.js
  docs/index.md
  docs/introduction/faq.md
  mkdocs.yml
  static/disqus.html
Labels: review

#170 Update index.md
  docs/index.md
  mkdocs.yml
Labels: review

#172 Update disqus.html
  static/disqus.html
Labels: review

#173 fix: fix pagetime display settings and word counting
  build.sh
  docs/_static/js/extra.js
  docs/index.md
  mkdocs.yml
Labels: review

#171 docs: add template for issue and pr
  .github/ISSUE_TEMPLATE/-----.md
  .github/ISSUE_TEMPLATE/---bug.md
  .github/pull_request_template.md
Labels: review

#175 add 素数计数函数
  docs/math/prime.md
Labels: review

#177 Update basic.md（修复「最小生成树」的链接）
  docs/graph/basic.md
Labels: good first issue

#176 remove toc in math/index
  docs/math/index.md
Labels: review

#180 update templates, add 矩阵乘法、简单的博弈论、分数规划
  .github/ISSUE_TEMPLATE/-----.md
  .github/ISSUE_TEMPLATE/---bug.md
  .github/pull_request_template.md
  docs/basic/binary.md
  docs/introduction/about.md
  docs/introduction/faq.md
  docs/math/game.md
  docs/math/matrix.md
  mkdocs.yml
Labels: review

#185 quick fix after quick reading.
  docs/string/sam.md
Labels: review

#186 add link to groups
  docs/index.md
Labels: review

#188 feat: update progress, minor fix on index.md
  README.md
  docs/index.md
  docs/intro/about.md
Labels: review

#190 add pencil icon to faq.md
  docs/intro/faq.md
Labels: review

#196 导言换行改成 <br />；修正几处 LaTeX 规范
  docs/math/misc.md
Labels: good first issue

#193 Update lca.md
  docs/graph/lca.md
Labels: good first issue

#215 Update pull_request_template.md
  .github/pull_request_template.md
Labels: review

#220 修改之前搬运的时候疏忽之处，以及去掉数据结构部分的分级
  README.md
  docs/dp/index.md
  mkdocs.yml
Labels: review

#226 fix zero...
  docs/string/sam.md
Labels: review

#227 fix: fix formula display
  docs/math/mobius.md
Labels: review

#239 multiple update on docs
  .github/CONTRIBUTING.md
  .github/pull_request_template.md
  README.md
  docs/ds/pb-ds/index.md
  docs/ds/pb-ds/priority-queue.md
  docs/intro/faq.md
  docs/misc/dsu-on-tree.md
  mkdocs.yml
Labels: review

#243 Update dfs.md
  docs/search/dfs.md
Labels: 内容需增修 / More details needed

#257 Fix page-time
  docs/_static/js/extra.js
Labels: good first issue

#259 fix #255 CI failing
  docs/ds/stl/priority_queue.md
  docs/ds/stl/vector.md
Labels: 等待合并 / Pending merge

#268 Update optimization.md
  docs/dp/optimization.md
Labels: 等待审核 / Pending review

#274 Feat: back to top
  build.sh
  docs/_static/css/extra.css
  mkdocs.yml
  static/disqus.html
  static/footer.html
Labels: 需要讨论 / discussion

#266 添加逆元
  docs/math/inverse.md
Labels: 等待其它 PR / Waiting other PRs

#286 Update splay,md
  docs/ds/splay.md
Labels: 等待合并 / Pending merge

#291 arrange formula
  docs/basic/binary.md
  docs/dp/index.md
  docs/dp/memo.md
  docs/ds/queue.md
  docs/ds/stack.md
  docs/graph/shortest-path.md
  docs/index.md
  docs/math/catalan.md
  docs/misc/cdq-divide.md
  docs/misc/io.md
  docs/misc/matrix-tree.md
  docs/misc/mo-algo.md
  docs/string/hash.md
  docs/string/kmp.md
Labels: 等待审核 / Pending review

#281 phi 和 varphi 的正确写法
  .github/pull_request_template.md
Labels: 需要讨论 / discussion

#285 Create map.md
  docs/ds/stl/map.md
Labels: 内容需增修 / More details needed, 需要讨论 / discussion

#295 完善了贪心部分
  docs/basic/greedy.md
Labels: 格式需修正 / Format fix needed

#299 Update priority_queue.md
  docs/ds/stl/priority_queue.md
Labels: 等待审核 / Pending review

#306 Update bezouts.md
  docs/math/bezouts.md
Labels: 格式需修正 / Format fix needed

#271 添加 Vim 介绍
  docs/intro/editors.md
  docs/intro/images/airline1.png
  docs/intro/images/airline2.png
  docs/intro/images/horrorstories.txt.jpg
  docs/intro/judgers.md
  mkdocs.yml
Labels: 等待审核 / Pending review

#316 update docs/ds/stl/map
  docs/ds/stl/map.md
Labels: 正在修锅 / Fix in progress
