Repository OI-wiki/OI-wiki, pull requests merged in 2018-09, with the labels that each got.

#328 feat: add favicon.ico
  docs/favicon.ico
  mkdocs.yml
Labels: 等待合并 / Pending merge

#261 Update shortest-path.md
  docs/graph/shortest-path.md
Labels: 等待审核 / Pending review, 需要讨论 / discussion

#330 Update bezouts.md
  docs/math/bezouts.md
Labels: 格式需修正 / Format fix needed

#327 feat: use InstantClick
  build.sh
  docs/_static/js/extra.js
  mkdocs.yml
  static/disqus.html
  static/footer.html
Labels: 等待合并 / Pending merge, 需要帮助 / help wanted, 需要讨论 / discussion, 高优先级 / P1

#354 Update segment.md
  docs/ds/segment.md
Labels: 等待审核 / Pending review

#323 补充2-SAT
  docs/graph/2-sat.md
  docs/graph/shortest-path.md
  docs/math/bignum.md
  docs/math/fft.md
Labels: 等待审核 / Pending review

#364 Create .gitattributes
  .gitattributes
Labels: 等待合并 / Pending merge

#367 更新了数学分类下的康托展开
  docs/math/cantor.md
Labels: good first issue

#368 逆元定义修改
  docs/math/inverse.md
Labels: good first issue

#369 Update game.md and upload game1.png
  docs/math/game.md
  docs/math/images/game1.png
Labels: good first issue

#386 填坑Matrix-Tree定理
  docs/misc/matrix-tree.md
Labels: 等待审核 / Pending review

#394 Update linear-equation.md
  docs/math/linear-equation.md
Labels: good first issue

#412 Update
  docs/basic/divide-and-conquer.md
  docs/dp/memo.md
  docs/search/optimization.md
  mkdocs.yml
Labels: 内容需增修 / More details needed

#447 Update bit.md
  docs/math/bit.md
Labels: 等待审核 / Pending review

#476 corrected a wrong word in tree-basic.md
  docs/graph/tree-basic.md
Labels: good first issue

#496 PR #348追加
  docs/search/index.md
Labels: 等待合并 / Pending merge
