Repository OI-wiki/OI-wiki, pull requests merged in 2019-10, with the labels that each got.

#1715 Update bit.md
  docs/math/bit.md
Labels: 等待审核 / Pending review

#1730 update suffix array
  docs/string/images/sa1.png
  docs/string/images/sa2.png
  docs/string/images/sa3.png
  docs/string/sa.md
Labels: 等待审核 / Pending review

#1738 添加「计算几何 - 反演变换」页面
  docs/geometry/images/inverse1.png
  docs/geometry/images/inverse2.png
  docs/geometry/images/inverse3.png
  docs/geometry/images/inverse4.png
  docs/geometry/inverse.md
  mkdocs.yml
Labels: 等待审核 / Pending review

#1672 Add 出题专题
  docs/intro/polygon.md
  docs/misc/random.md
  docs/topic/problemsetting.md
  mkdocs.yml
Labels: 等待审核 / Pending review

#1666 Update common-tricks.md
  docs/intro/common-tricks.md
Labels: 等待审核 / Pending review

#1735 Update opt.md
  docs/search/opt.md
Labels: 等待审核 / Pending review

#1749 Update basic.md
  docs/lang/basic.md
Labels: 等待审核 / Pending review

#1761 fix typo in intro of graph
  docs/graph/index.md
Labels: 等待审核 / Pending review

#1758 update iterator
  docs/lang/csl/container.md
  docs/lang/csl/iterator.md
Labels: 等待审核 / Pending review, 需要讨论 / discussion

#1698 Update notepad++
  docs/intro/editor/images/npp-install-1.png
  docs/intro/editor/images/npp-install-2.png
  docs/intro/editor/images/npp-install-3.png
  docs/intro/editor/images/npp-lang.gif
  docs/intro/editor/images/npp-logo.webp
  docs/intro/editor/images/npp-macro-rec.gif
  docs/intro/editor/images/npp-macro-use.gif
  docs/intro/editor/images/npp-replace.png
  docs/intro/editor/images/npp-search.png
  docs/intro/editor/images/npp-settings-1.png
  docs/intro/editor/images/npp-settings-2.png
  docs/intro/editor/npp.md
Labels: 内容冲突 / Content Conflict, 等待合并 / Pending merge

#1770 Add links to open-source OJ projects
  docs/intro/resources.md
Labels: 等待审核 / Pending review

#1775 fix fast io template
  docs/misc/io.md
Labels: 等待审核 / Pending review

#1777 add multimap
  docs/lang/csl/associative-container.md
Labels: 等待审核 / Pending review

#1778 将 C++ 新特性中的 array 部分内容合并到 STL 中
  docs/lang/csl/sequence-container.md
  docs/lang/new.md
Labels: 等待审核 / Pending review

#1789 add Johnson 全源最短路径算法
  docs/graph/images/shortest-path1.png
  docs/graph/images/shortest-path2.png
  docs/graph/shortest-path.md
Labels: 等待审核 / Pending review

#1794 :bug:fix(binary heap): fix typo
  docs/ds/binary-heap.md
Labels: 等待审核 / Pending review
