Repository OI-wiki/OI-wiki, pull requests merged in 2019-09, with the labels that each got.

#1618 对AC自动机中的tr数组增加一些解释
  docs/string/ac-automaton.md
Labels: 等待合并 / Pending merge

#1656 析合树本源段举例修正
  docs/ds/divide-combine.md
Labels: 等待审核 / Pending review

#1575 feat: 添加 Python 部分内容 && ImgBot
  docs/ds/images/avl1.jpg
  docs/ds/images/avl2.jpg
  docs/ds/images/avl3.jpg
  docs/ds/images/cartesian-tree1.png
  docs/ds/images/cartesian-tree2.png
  docs/ds/images/kdt1.jpg
  docs/ds/images/kdt2.jpg
  docs/ds/images/linked-list1.png
  docs/ds/images/linked-list2.png
  docs/ds/images/linked-list3.png
  docs/geometry/images/triangulation-1.png
  docs/graph/flow/images/1152.png
  docs/graph/flow/images/2148.png
  docs/graph/flow/images/2150.png
  docs/graph/images/scc1.png
  docs/graph/images/treehash1.png
  docs/intro/editor/images/vscode-2.png
  docs/intro/editor/images/vscode-3.png
  docs/intro/images/alipay.png
  docs/intro/images/cf-tool1.jpg
  docs/intro/images/cf-tool2.jpg
  docs/intro/images/htc-1.png
  docs/intro/images/htc-2.png
  docs/intro/images/htc-4.png
  docs/intro/images/htc-5.png
  docs/intro/images/htc-6.png
  docs/intro/images/htc-7.png
  docs/intro/images/htc-8.png
  docs/intro/images/htc-9.png
  docs/intro/images/latex-for-beginners-1.png
  docs/intro/images/latex-for-beginners-10.png
  docs/intro/images/latex-for-beginners-11.png
  docs/intro/images/latex-for-beginners-12.png
  docs/intro/images/latex-for-beginners-13.png
  docs/intro/images/latex-for-beginners-14.png
  docs/intro/images/latex-for-beginners-15.png
  docs/intro/images/latex-for-beginners-2.png
  docs/intro/images/latex-for-beginners-3.png
  docs/intro/images/latex-for-beginners-4.png
  docs/intro/images/latex-for-beginners-5.png
  docs/intro/images/latex-for-beginners-6.png
  docs/intro/images/latex-for-beginners-7.png
  docs/intro/images/latex-for-beginners-8.png
  docs/intro/images/latex-for-beginners-9.png
  docs/intro/images/wechat.png
  docs/lang/csl/images/container1.png
  docs/lang/images/python1.png
  docs/lang/images/python2.png
  docs/lang/python.md
  docs/misc/images/stern-brocot1.png
  docs/string/images/ac-automaton1.png
  docs/string/images/ac-automaton2.png
  docs/string/images/ac-automaton3.png
  docs/string/images/ac-automaton4.png
  docs/string/images/trie1.png
Labels: 等待审核 / Pending review

#1658 Update job-order.md
  docs/misc/job-order.md
Labels: 等待审核 / Pending review

#1661 add 语言基础/循环
  docs/lang/images/loop1.png
  docs/lang/images/loop2.png
  docs/lang/images/loop3.png
  docs/lang/loop.md
Labels: 等待审核 / Pending review

#1659 析合树模板查询传参错误
  docs/ds/divide-combine.md
Labels: 等待审核 / Pending review

#1649 新增动态DP
  docs/dp/dynamic.md
  docs/dp/images/dynamic.png
Labels: 等待合并 / Pending merge

#1671 修正平面向量线性运算的公式
  docs/math/vector.md
Labels: 等待审核 / Pending review

#1673 fix link of bignum.md
  docs/math/bignum.md
Labels: 等待审核 / Pending review

#1679 改正后缀自动机部分引理1的叙述错误
  docs/string/sam.md
Labels: 等待审核 / Pending review

#1680 fix typo in math
  docs/math/complex.md
  docs/math/vector.md
Labels: 等待审核 / Pending review

#1677 Update bridge.md
  docs/graph/bridge.md
Labels: 等待审核 / Pending review

#1664 add Python相关, add STL相关, fix 一些翻译
  docs/ds/queue.md
  docs/intro/resources.md
  docs/lang/c-cpp.md
  docs/lang/const.md
  docs/lang/csl/algorithm.md
  docs/lang/csl/container.md
  docs/lang/csl/index.md
  docs/lang/csl/iterator.md
  docs/lang/csl/sequence-container.md
  docs/lang/helloworld.md
  docs/lang/new.md
  docs/lang/op.md
  docs/lang/python.md
  docs/lang/reference.md
  mkdocs.yml
Labels: 等待审核 / Pending review

#1660 Update branch.md
  docs/lang/branch.md
Labels: 等待审核 / Pending review

#1662 add C++语法基础
  docs/lang/basic.md
Labels: 等待审核 / Pending review

#1665 Update binary-heap.md
  docs/ds/binary-heap.md
Labels: 等待审核 / Pending review

#1687 fix: 修改动态 dp 页面中的公式 typo
  docs/dp/dynamic.md
Labels: 等待审核 / Pending review

#1652 add LGV lemma
  docs/graph/lgv.md
  mkdocs.yml
Labels: 等待审核 / Pending review

#1686 fix definition of ICG
  docs/math/game-theory.md
Labels: 等待审核 / Pending review, 需要讨论 / discussion

#1706 Add shadow.css
  docs/_static/css/extra.css
  docs/intro/htc.md
Labels: 等待审核 / Pending review, 需要讨论 / discussion

#1711 :bug: fix(iter): 修复对 rend 的错误解释
  docs/lang/csl/iterator.md
Labels: 等待审核 / Pending review

#1681 Fix：修订最大流和费用流页面以及一些其他页面的格式
  docs/ds/dsu.md
  docs/graph/bridge.md
  docs/graph/flow/max-flow.md
  docs/graph/flow/min-cost.md
Labels: 等待审核 / Pending review

#1549 Update ett.md
  docs/ds/ett.md
Labels: 需要帮助修正格式 / Help needed for format

#1718 更新树链剖分部分若干伪代码
  docs/graph/hld.md
  docs/intro/editor/devcpp.md
Labels: 等待审核 / Pending review

#1717 修复第n+1个点的点值表示法的typo
  docs/math/poly/fft.md
Labels: 等待审核 / Pending review

#1697 add 自动机 & 序列自动机 & 字符串板块其它内容
  docs/string/automaton.md
  docs/string/general-sam.md
  docs/string/hash.md
  docs/string/images/automaton1.png
  docs/string/index.md
  docs/string/match.md
  docs/string/seq-automaton.md
  docs/string/trie.md
  mkdocs.yml
Labels: 等待审核 / Pending review

#1731 更新树链剖分
  docs/graph/hld.md
  docs/graph/images/hld2.png
Labels: 等待审核 / Pending review
