Repository OI-wiki/OI-wiki, pull requests merged in 2019-07, with the labels that each got.

#1281 feat: 增加高维前缀和
  docs/basic/prefix-sum.md
Labels: 等待合并 / Pending merge, 等待审核 / Pending review

#982 feat: 补充网络流最大流
  docs/graph/flow.md
  docs/graph/flow/images/1152.png
  docs/graph/flow/images/2148.png
  docs/graph/flow/images/2149.gif
  docs/graph/flow/images/2150.png
  docs/graph/flow/max-flow.md
Labels: 内容冲突 / Content Conflict, 需要处理 / Need Processing

#1372 Update: 更新AC自动机
  docs/string/ac-automaton.md
  docs/string/images/ac-automaton1.gif
  docs/string/images/ac-automaton1.png
  docs/string/images/ac-automaton2.gif
  docs/string/images/ac-automaton2.png
  docs/string/images/ac-automaton3.gif
  docs/string/images/ac-automaton3.png
  docs/string/images/ac-automaton4.png
Labels: 需要讨论 / discussion
