Repository OI-wiki/OI-wiki, pull requests merged in 2019-08, with the labels that each got.

#1512 Update quick-sort.md and stl-sort.md
  docs/basic/quick-sort.md
  docs/basic/stl-sort.md
Labels: 等待合并 / Pending merge

#1503 把创作格式要求单独建一个页面
  docs/intro/htc.md
  docs/intro/images/htc-1.png
  docs/intro/images/htc-2.png
  docs/intro/images/htc-4.png
  docs/intro/images/htc-5.png
  docs/intro/images/htc-6.png
  docs/intro/images/htc-7.png
  docs/intro/images/htc-8.png
  docs/intro/images/htc-9.png
  mkdocs.yml
Labels: 等待审核 / Pending review

#1538 feat(array): add array
  docs/lang/array.md
Labels: 等待审核 / Pending review

#1559 feat: 添加 LaTeX 入门
  docs/intro/images/latex-for-beginners-1.png
  docs/intro/images/latex-for-beginners-10.png
  docs/intro/images/latex-for-beginners-11.png
  docs/intro/images/latex-for-beginners-12.png
  docs/intro/images/latex-for-beginners-13.png
  docs/intro/images/latex-for-beginners-14.png
  docs/intro/images/latex-for-beginners-15.png
  docs/intro/images/latex-for-beginners-2.png
  docs/intro/images/latex-for-beginners-3.png
  docs/intro/images/latex-for-beginners-4.png
  docs/intro/images/latex-for-beginners-5.png
  docs/intro/images/latex-for-beginners-6.png
  docs/intro/images/latex-for-beginners-7.png
  docs/intro/images/latex-for-beginners-8.png
  docs/intro/images/latex-for-beginners-9.png
  docs/intro/latex.md
  mkdocs.yml
Labels: 等待审核 / Pending review

#1560 docs(mo-algo): 代码折叠与格式规范
  docs/misc/mo-algo.md
Labels: 等待审核 / Pending review

#1585 修复”动态规划部分简介“中的错别字
  docs/dp/index.md
Labels: 等待合并 / Pending merge

#1553 feat: 添加 Sqrt Tree
  docs/ds/sqrt-tree.md
  mkdocs.yml
Labels: 等待合并 / Pending merge

#1565 修改 emacs.md 中的错误并完善
  docs/intro/editor/emacs.md
  docs/lang/op.md
Labels: 等待合并 / Pending merge

#1591 fix something about STL container
  docs/lang/csl/container.md
Labels: 等待合并 / Pending merge

#1588 修改：动态规划部分简介-最长不下降子序列-解法一-ans初始值
  docs/dp/index.md
Labels: 等待审核 / Pending review

#1589 修复 Four Russian 部分的复杂度公式
  docs/topic/rmq.md
Labels: 等待审核 / Pending review

#1598 add 只使用启发式合并的并查集
  docs/ds/dsu.md
Labels: 等待合并 / Pending merge

#1592 feat: 最小生成树：add Boruvka 算法
  docs/graph/images/mst-1.gif
  docs/graph/mst.md
Labels: 等待审核 / Pending review

#1615 fix typo in dsu
  docs/ds/dsu.md
Labels: 等待审核 / Pending review

#1604 update htc: 添加伪代码格式等
  docs/intro/htc.md
Labels: 等待审核 / Pending review

#1590 container-adapter.md 添加 std::stack 和 std::queue
  docs/lang/csl/container-adapter.md
Labels: 等待审核 / Pending review

#1607 add 二分图染色的构造性证明+修复一个小锅
  docs/graph/color.md
Labels: 等待合并 / Pending merge

#1620 去掉渐进表达式中非指数的对数的底数
  docs/dp/index.md
  docs/dp/opt/binary-knapsack.md
  docs/ds/block-array.md
  docs/ds/bst.md
  docs/ds/cartesian-tree.md
  docs/ds/divide-combine.md
  docs/ds/kdt.md
  docs/ds/lct.md
  docs/ds/persistent-heap.md
  docs/ds/persistent-in-bit.md
  docs/ds/queue.md
  docs/ds/seg-beats.md
  docs/ds/seg.md
  docs/ds/sqrt-tree.md
  docs/ds/treap.md
  docs/graph/dynamic-tree-divide.md
  docs/graph/kth-path.md
  docs/graph/prufer.md
  docs/graph/tree-divide.md
  docs/math/fibonacci.md
  docs/math/inclusion-exclusion-principle.md
  docs/math/lucas.md
  docs/math/matrix.md
  docs/math/poly/fft.md
  docs/math/quick-pow.md
  docs/misc/cdq-divide.md
  docs/misc/complexity.md
  docs/misc/parallel-binsearch.md
Labels: 等待审核 / Pending review

#1609 update htc：添加了分数使用规定
  docs/intro/htc.md
Labels: 等待审核 / Pending review

#1625 update zoj link in resources.md
  docs/intro/resources.md
Labels: 等待审核 / Pending review

#1606 加入了P、NP、coNP、NPC、非确定型图灵机的内容
  docs/misc/cc-basic.md
Labels: 等待审核 / Pending review

#1603 添加 eclipse 编辑器食用指北
  docs/intro/editor/eclipse.md
  docs/intro/editor/images/eclipse1-1.png
  docs/intro/editor/images/eclipse1-2.png
  docs/intro/editor/images/eclipse1-3.png
  docs/intro/editor/images/eclipse1-4.png
  docs/intro/editor/images/eclipse1-5.png
  docs/intro/editor/images/eclipse1-6.png
  docs/intro/editor/images/eclipse1-7.png
  docs/intro/editor/images/eclipse1-8.png
  docs/intro/editor/images/eclipse1.png
  docs/intro/editor/images/eclipse2.png
  docs/intro/editor/images/eclipse3.png
  docs/intro/editor/images/eclipse4.png
  docs/intro/editor/images/eclipse5.png
  docs/intro/editor/images/eclipse6.png
  docs/intro/editor/images/eclipse7.png
Labels: 等待审核 / Pending review

#1614 更新排序相关内容
  docs/basic/bubble-sort.md
  docs/basic/bucket-sort.md
  docs/basic/counting-sort.md
  docs/basic/heap-sort.md
  docs/basic/insertion-sort.md
  docs/basic/merge-sort.md
  docs/basic/radix-sort.md
  docs/basic/selection-sort.md
  docs/basic/sort-intro.md
  docs/basic/stl-sort.md
  mkdocs.yml
Labels: 等待审核 / Pending review

#1577 细化数学相关内容的分类
  docs/geometry/2d.md
  docs/geometry/index.md
  docs/math/complex.md
  docs/math/index.md
  docs/math/lucas.md
  docs/math/polar-coordinate.md
  docs/math/primitive-root.md
  docs/math/vector.md
  mkdocs.yml
Labels: 等待合并 / Pending merge, 需要处理 / Need Processing

#1634 fix(htc): fix typo
  docs/intro/htc.md
Labels: 等待审核 / Pending review

#1631 fix #1616+#1388
  docs/graph/images/mst5.png
  docs/graph/images/mst6.png
  docs/graph/mst.md
Labels: 等待审核 / Pending review

#1633 fix：修正树链剖分伪代码格式
  docs/graph/hld.md
Labels: 需要讨论 / discussion

#1638 Update bit.md
  docs/math/bit.md
Labels: 等待审核 / Pending review

#1640 补充筛法求约数个数
  docs/math/sieve.md
Labels: 等待审核 / Pending review
