Repository OI-wiki/OI-wiki, pull requests merged in 2019-11, with the labels that each got.

#1793 add unordered container
  docs/graph/shortest-path.md
  docs/lang/csl/unordered-container.md
Labels: 等待审核 / Pending review

#1760 添加“线性递推”页面
  docs/math/linear-recurrence.md
  mkdocs.yml
Labels: 等待审核 / Pending review, 需要处理 / Need Processing, 需要讨论 / discussion

#1799 关于关联式容器中set和map的insert的返回值
  docs/lang/csl/associative-container.md
Labels: 等待审核 / Pending review

#1807 fix(frac-programming): fix typo
  docs/misc/frac-programming.md
Labels: 等待审核 / Pending review

#1790 更新01背包和完全背包的核心代码和AC代码,对01背包和前面的记忆化搜索方法进行了联系
  docs/dp/knapsack.md
Labels: 等待审核 / Pending review

#1781 更改一个锅了的伪代码
  docs/ds/cartesian-tree.md
Labels: 等待审核 / Pending review

#1808 Update emacs.md 更新配置等部分
  docs/intro/editor/emacs.md
Labels: 等待审核 / Pending review

#1755 增修「计算几何-反演变换」& 更正「数学-莫比乌斯反演」中的公式错误
  docs/geometry/inverse.md
  docs/math/mobius.md
Labels: 等待合并 / Pending merge

#1834 fix(docs/intro/faq): fix hosts
  docs/intro/faq.md
Labels: 等待审核 / Pending review

#1830 fix: 莫比乌斯反演中公式问题
  docs/math/mobius.md
Labels: 等待审核 / Pending review

#1826 Revert "添加 FeatHub"
  README.md
Labels: 等待审核 / Pending review

#1811 add 运算符优先级表, update 位运算
  docs/lang/op.md
  docs/math/bit.md
Labels: 等待审核 / Pending review

#1841 [Update seg.md] 修 typo
  docs/ds/seg.md
Labels: 等待审核 / Pending review

#1827 fix(centroid): move tree-misc to tree-centroid and update it
  docs/graph/tree-centroid.md
  docs/graph/tree-misc.md
  mkdocs.yml
Labels: 等待审核 / Pending review

#1822 fix(dp): move old index to basic; add new index
  docs/dp/basic.md
  docs/dp/index.md
  mkdocs.yml
Labels: 等待审核 / Pending review

#1786 Create&Update chord.md
  docs/graph/chord.md
  mkdocs.yml
Labels: 等待审核 / Pending review

#1824 fix(math,geometry): update index.md & move files
  docs/geometry/2d.md
  docs/geometry/index.md
  docs/geometry/polar-coordinate.md
  docs/math/index.md
  docs/math/notation.md
  mkdocs.yml
Labels: 等待审核 / Pending review

#1823 fix(ds): update index.md
  docs/ds/index.md
Labels: 等待审核 / Pending review

#1750 Update container.md
  docs/lang/csl/container.md
Labels: 等待取消修改请求 / Pending Cancel Changes Request

#1813 补充 ST 表相关内容
  docs/ds/sparse-table.md
Labels: 等待审核 / Pending review

#1849 add namespace
  docs/lang/basic.md
  docs/lang/namespace.md
  mkdocs.yml
Labels: 等待审核 / Pending review

#1859 重写计算理论基础 & 增加小 o 符号和小 ω 符号
  docs/misc/cc-basic.md
  docs/misc/complexity.md
Labels: 等待审核 / Pending review
