Repository OI-wiki/OI-wiki, pull requests merged in 2019-04, with the labels that each got.

#1128 树分块
  docs/ds/tree-decompose.md
Labels: 需要讨论 / discussion

#1136 添加/修正 bitset 相关内容 & 树剖的一个小改动
  docs/ds/stl/bitset.md
  docs/graph/heavy-light-decomposition.md
Labels: 等待审核 / Pending review

#1129 Update linear-programming.md
  docs/math/linear-programming.md
Labels: 等待审核 / Pending review

#1134 Update construction.md
  docs/basic/construction.md
Labels: 等待审核 / Pending review

#1140 更新 数据结构部分简介
  docs/ds/index.md
Labels: 等待审核 / Pending review, 需要讨论 / discussion

#1151 :pen: Update resources.md
  docs/intro/resources.md
Labels: 需要讨论 / discussion
