Repository OI-wiki/OI-wiki, pull requests merged in 2019-03, with the labels that each got.

#996 feat: 增加最后一道例题的题解
  docs/math/mobius.md
Labels: 等待合并 / Pending merge

#981 更新莫比乌斯反演
  docs/math/mobius.md
Labels: 等待审核 / Pending review

#1031 Update sa.md
  docs/string/sa.md
Labels: 内容需增修 / More details needed, 需要帮助 / help wanted, 需要讨论 / discussion

#969 Update mode.md
  docs/intro/mode.md
Labels: 需要讨论 / discussion

#1098 [WIP]fix: Update distance.md
  docs/misc/distance.md
  docs/misc/images/manhattan-dis.png
Labels: 正在修锅 / Fix in progress, 需要帮助 / help wanted

#1081 Update pam.md
  docs/string/images/pam1.png
  docs/string/images/pam2.png
  docs/string/pam.md
Labels: 内容需增修 / More details needed, 格式需修正 / Format fix needed
