Repository OI-wiki/OI-wiki, pull requests merged in 2020-02, with the labels that each got.

#1814 补充了倍增的内容
  docs/basic/binary-acc.md
Labels: 等待审核 / Pending review

#1964 Update euler.md
  docs/math/euler.md
Labels: 等待审核 / Pending review

#1961 fix equation in gcd.md
  docs/math/gcd.md
Labels: 等待审核 / Pending review

#1968 Update index.md
  docs/lang/csl/index.md
  docs/math/euler.md
Labels: 等待合并 / Pending merge

#1928 修复公式
  docs/math/poly/ln-exp.md
Labels: 等待合并 / Pending merge

#1844 Update mistakes.md ： 增加常见错误
  docs/intro/common-mistakes.md
Labels: 等待审核 / Pending review

#1965 Update mobius.md
  docs/math/mobius.md
Labels: 等待审核 / Pending review

#1971 du(math): put codeblock into notes
  docs/math/du.md
Labels: 等待合并 / Pending merge

#1974 Branch.md 修格式以及 typo
  docs/lang/branch.md
Labels: 等待审核 / Pending review

#1966 给费马小定理加了个证明 Update fermat.md
  docs/math/fermat.md
Labels: 等待审核 / Pending review

#1980 修正一些 LaTeX 问题
  docs/math/bsgs.md
Labels: 等待合并 / Pending merge

#1975 修正回文自动机中的书写错误
  docs/string/pam.md
Labels: 等待审核 / Pending review

#1984 Update geany.md
  docs/lang/editor/geany.md
  mkdocs.yml
Labels: 等待审核 / Pending review

#1990 Update sa.md
  docs/string/sa.md
Labels: 等待合并 / Pending merge

#1979 Update insertion-sort.md
  docs/basic/insertion-sort.md
Labels: 等待审核 / Pending review

#1982 fix(lang/basic): 标识符的定义
  docs/lang/basic.md
Labels: 等待审核 / Pending review

#1973 整理语言基础部分的目录，并修一下 Loop.md 的锅
  docs/lang/loop.md
  mkdocs.yml
Labels: Pending merge / 等待合并

#1972 增加 dsu 时间复杂度证明相关内容
  docs/ds/dsu.md
  docs/ds/dsu_complexy.md
  docs/ds/images/dsu_complexy1.png
Labels: Pending review / 等待审核

#1995 Update bound.md
  docs/graph/flow/bound.md
Labels: Pending apply suggestions / 等待采纳建议, Pending review / 等待审核

#1846 euler.md：修 typo 和补充内容
  docs/graph/euler.md
  docs/images/euler1.png
  docs/images/euler2.png
Labels: Pending review / 等待审核

#1959 添加关于 Ackermann 函数的内容
  docs/ds/dsu.md
Labels: Pending merge / 等待合并

#1996 修 rmq.md 中的一个小 bug
  docs/topic/rmq.md
Labels: Pending review / 等待审核

#1999 Update binary.md
  docs/basic/binary.md
Labels: Pending merge / 等待合并

#2000 perf(banner): compress image
  docs/images/wordArt.png
  docs/images/wordArt.webp
  docs/index.md
Labels: Pending review / 等待审核

#2016 ddp:put codeblock into details
  docs/dp/dynamic.md
Labels: Pending review / 等待审核

#2013 增加了一些图论基础概念
  docs/graph/concept.md
Labels: Pending review / 等待审核

#1951 Update sqrt.md
  docs/math/poly/sqrt.md
Labels: Pending review / 等待审核
