Repository OI-wiki/OI-wiki, pull requests merged in 2020-07, with the labels that each got.

#2277 添加了压位高精度的内容
  docs/math/bignum.md
Labels: Pending review / 等待审核

#2390 添加变量类型转换相关内容
  docs/lang/op.md
  docs/lang/var.md
Labels: Pending review / 等待审核

#2387 更新了二分图匹配相关内容
  docs/graph/bi-graph.md
  docs/topic/graph-matching/bigraph-match.md
  docs/topic/graph-matching/bigraph-weight-match.md
  docs/topic/graph-matching/graph-match.md
Labels: Pending review / 等待审核

#2407 MathJax fixes for LaTeX export tools
  docs/ds/fenwick.md
  docs/ds/sqrt-tree.md
  docs/graph/flow.md
  docs/graph/flow/max-flow.md
  docs/graph/tree-hash.md
  docs/intro/format.md
  docs/math/combination.md
  docs/math/euler.md
  docs/math/fibonacci.md
  docs/math/mobius.md
  docs/math/poly/fft.md
  docs/math/poly/lagrange.md
  docs/math/simplex.md
  docs/misc/stern-brocot.md
  docs/string/bm.md
  docs/string/sam.md
Labels: Discussion / 需要讨论, help wanted / 需要帮助

#2213 添加了命令行使用的相关内容
  docs/topic/cmd.md
  mkdocs.yml
Labels: Discussion / 需要讨论, Pending review / 等待审核

#2422 更新格式手册
  docs/intro/format.md
  docs/math/matrix.md
  docs/topic/cmd.md
Labels: Discussion / 需要讨论, Pending review / 等待审核, help wanted / 需要帮助

#2455 添加了李超线段树相关内容
  docs/ds/images/li-chao-tree1.png
  docs/ds/images/li-chao-tree2.png
  docs/ds/images/li-chao-tree3.png
  docs/ds/images/li-chao-tree4.png
  docs/ds/li-chao-tree.md
  mkdocs.yml
Labels: Pending review / 等待审核

#2470 更改题目网址
  docs/math/bsgs.md
Labels: Pending review / 等待审核
