Repository OI-wiki/OI-wiki, pull requests merged in 2020-01, with the labels that each got.

#1771 fix(doc/lang/helloworld): 强调C与C++区别
  docs/lang/helloworld.md
Labels: 等待审核 / Pending review

#1889 Update helloworld.md
  docs/lang/helloworld.md
Labels: 等待审核 / Pending review

#1888 增加Java语言[Finish 🎉]
  docs/lang/images/java1.png
  docs/lang/images/java2.png
  docs/lang/images/java3.png
  docs/lang/images/java4.png
  docs/lang/images/java5.png
  docs/lang/images/java6.png
  docs/lang/java.md
Labels: 等待审核 / Pending review

#1915 docs/lang/java.md
  docs/lang/java.md
Labels: 等待审核 / Pending review

#1858 更新回文树的内容
  docs/string/images/pam3.png
  docs/string/images/pam4.png
  docs/string/images/pam5.png
  docs/string/images/pam6.png
  docs/string/pam.md
  mkdocs.yml
Labels: 等待审核 / Pending review, 页面标题有改动 / Title Changed

#1923 修复一些微小的错误
  docs/intro/latex.md
Labels: 等待审核 / Pending review

#1904 更新省选相关内容
  docs/intro/oi.md
Labels: 需要讨论 / discussion

#1728 Update bst.md
  docs/ds/bst.md
Labels: 等待审核 / Pending review, 高优先级 / P1

#1848 feat(graph): merge index, basic, misc into concept and save, add new index
  docs/graph/basic.md
  docs/graph/bcc.md
  docs/graph/concept.md
  docs/graph/cut.md
  docs/graph/index.md
  docs/graph/lgv.md
  docs/graph/misc.md
  docs/graph/mst.md
  docs/graph/save.md
  docs/graph/scc.md
  docs/graph/shortest-path.md
  mkdocs.yml
Labels: 等待审核 / Pending review, 评论区 label 待更新 / Label Needs Update

#1641 fix #1246
  docs/graph/hld.md
Labels: 内容需增修 / More details needed, 等待审核 / Pending review, 需要处理 / Need Processing

#1873 [ds/bit.md]增加一些Tricks讲解
  docs/ds/bit.md
Labels: 内容需增修 / More details needed, 等待采纳建议 / Pending apply suggestions

#1832 fix 许多语言基础的问题
  docs/lang/array.md
  docs/lang/basic.md
  docs/lang/branch.md
  docs/lang/var.md
Labels: 等待审核 / Pending review
