Repository OI-wiki/OI-wiki, pull requests merged in 2020-08, with the labels that each got.

#2471 添加了 伯努利数 的内容
  docs/math/bernoulli.md
  mkdocs.yml
Labels: Pending review / 等待审核

#2451 fix: misuses of formula
  docs/ds/bst.md
Labels: Discussion / 需要讨论

#2506 更新 geany.md
  docs/lang/editor/geany.md
Labels: Pending apply suggestions / 等待采纳建议

#2502 添加了对多个字母组成的变量的格式要求
  docs/intro/format.md
Labels: Pending review / 等待审核

#2491 字符串hash：修改评论中提出的问题
  docs/string/hash.md
Labels: Pending review / 等待审核

#2268 refactor (resources.md, common-mistakes.md, common-tricks.md) 对页面进行格式化
  docs/contest/common-mistakes.md
  docs/contest/common-tricks.md
  docs/contest/resources.md
Labels: Pending review / 等待审核

#2535 增加了2-SAT输出一个可行解的例题
  docs/graph/2-sat.md
Labels: Pending review / 等待审核

#2539 修复莫队代码中循环顺序的问题
  docs/misc/mo-algo.md
Labels: Pending review / 等待审核

#2485 feat: 二维数论分块
  docs/math/mobius.md
Labels: Pending review / 等待审核

#2526 完善Integral内容
  docs/math/integral.md
Labels: Pending review / 等待审核

#2597 添加了重载运算符内容
  docs/lang/op-overload.md
  mkdocs.yml
Labels: Pending review / 等待审核

#2580 添加了 pollard-rho算法
  docs/math/pollard-rho.md
  mkdocs.yml
Labels: Pending review / 等待审核
