Repository OI-wiki/OI-wiki, pull requests merged in 2020-10, with the labels that each got.

#2584 Roadmap Chapter 1
  docs/contest/roadmap.md
Labels: Discussion / 需要讨论, Need Processing / 需要处理, Pending review / 等待审核, div. 1, help wanted / 需要帮助, 高优先级 / P1

#2148 添加了 Pascal 转 C++ 中引用相关内容。
  docs/lang/pas-cpp.md
Labels: Pending apply suggestions / 等待采纳建议, Pending review / 等待审核

#2704 修订VS Code相关内容
  docs/tools/editor/images/vscode-4.png
  docs/tools/editor/images/vscode-5.gif
  docs/tools/editor/images/vscode-6.png
  docs/tools/editor/vscode.md
Labels: Pending review / 等待审核

#2672 补充shortest-path内容
  docs/graph/shortest-path.md
Labels: Need Processing / 需要处理

#2677 增加dp内容
  docs/dp/opt/quadrangle.md
Labels: Need Processing / 需要处理

#2742 费用流的SSP算法，原先把名字误作MCMF，这里修正
  docs/graph/flow/min-cost.md
Labels: Need Processing / 需要处理
