Repository OI-wiki/OI-wiki, pull requests merged in 2021-06, with the labels that each got.

#3239 错字修改 gray-code.md
  docs/misc/gray-code.md
Labels: Amend Commit Msg

#3240 修复了FFT页面的一些typo
  docs/math/poly/fft.md
Labels: Amend Commit Msg

#3244 fix: 笔误
  docs/math/lucas.md
Labels: Amend Commit Msg

#3235 feat(wsl): 增加Win10访问WSL子系统目录和文件的内容
  docs/tools/wsl.md
Labels: Amend Commit Msg

#2627 feat: add Git
  docs/intro/htc.md
  docs/tools/git.md
  docs/tools/images/git1.png
  docs/tools/images/git10.png
  docs/tools/images/git2.png
  docs/tools/images/git3.png
  docs/tools/images/git4.png
  docs/tools/images/git5.png
  docs/tools/images/git6.png
  docs/tools/images/git7.png
  docs/tools/images/git8.png
  docs/tools/images/git9.png
  mkdocs.yml
Labels: Pending review / 等待审核

#3252 Fix a typo in quad-residue.md
  docs/math/quad-residue.md
Labels: Amend Commit Msg, Use Squash

#3255 proposal: store source file with image file
  docs/intro/format.md
Labels: Discussion / 需要讨论
