Repository OI-wiki/OI-wiki, pull requests merged in 2021-02, with the labels that each got.

#2735 add 二分和CDQ/Splay配合斜率优化
  docs/dp/opt/slope.md
Labels: Pending review / 等待审核

#2634 补充crt内容
  docs/lang/basic.md
  docs/math/crt.md
Labels: Need Processing / 需要处理, Waiting other PRs / 等待其它 PR

#3001 修正比较子串大小关系内容
  docs/string/sa.md
Labels: Pending review / 等待审核

#2721 style[backtracking.md]: 回溯法
  docs/search/backtracking.md
Labels: Need Processing / 需要处理
