Repository OI-wiki/OI-wiki, pull requests merged in 2021-07, with the labels that each got.

#3296 Fix typo in sublime3.md
  docs/tools/editor/sublime3.md
Labels: Amend Commit Msg

#3301 fix(basic/binary): expressions and appearance
  docs/basic/binary.md
Labels: Use Squash

#3288 feat: Add MPM Algorithm
  docs/basic/complexity.md
  docs/contest/common-mistakes.md
  docs/ds/persistent-balanced.md
  docs/graph/flow/max-flow.md
  docs/intro/thanks.md
  docs/lang/func.md
  docs/lang/pb-ds/tree.md
  docs/math/bsgs.md
  docs/math/eulerian.md
  docs/math/linear-programming.md
  docs/math/stirling.md
  docs/tools/editor/emacs.md
  docs/tools/editor/sublime3.md
  docs/tools/git.md
Labels: Amend Commit Msg, Use Squash

#3308 feat(math/gen-func/dgf): add Dirichlet series generating function
  docs/basic/binary.md
  docs/basic/divide-and-conquer.md
  docs/basic/enumerate.md
  docs/ds/fenwick.md
  docs/graph/flow.md
  docs/math/gen-func/dgf.md
  mkdocs.yml
  scripts/render_math_worker.js
Labels: Pending review / 等待审核

#3321 refactor(graph/tree-hash): Vectorize figure
  docs/basic/bubble-sort.md
  docs/basic/counting-sort.md
  docs/basic/insertion-sort.md
  docs/basic/merge-sort.md
  docs/basic/quick-sort.md
  docs/basic/selection-sort.md
  docs/basic/tournament-sort.md
  docs/graph/images/tree-hash1-hack.svg
  docs/graph/images/tree-hash1-hack.tex
  docs/graph/images/treehash1.png
  docs/graph/tree-hash.md
Labels: Amend Commit Msg

#3278 Fix linear-recurrence
  docs/math/linear-recurrence.md
Labels: Use Squash
