Repository OI-wiki/OI-wiki, pull requests merged in 2022-06, with the labels that each got.

#3950 feat(docs/math/poly/lagrange.md): 添加横坐标是连续整数的拉格朗日插值
  docs/math/code/poly/lagrange/lagrange_2.cpp
  docs/math/examples/poly/lagrange/lagrange_2.ans
  docs/math/examples/poly/lagrange/lagrange_2.in
  docs/math/poly/lagrange.md
Labels: Pending apply suggestions / 等待采纳建议, No Response / 失去响应

#3877 feat(math/poly/cntt): introduction to CNTT
  docs/math/poly/cntt.md
  mkdocs.yml
Labels: Pending merge / 等待合并

#3897 refactor(ds/li-chao-tree)：重构插入线段部分，换为逻辑更简单代码更简洁的实现。
  docs/ds/code/li-chao-tree/li-chao-tree_1.cpp
  docs/ds/li-chao-tree.md
Labels: No Response / 失去响应

#4001 fix: 修复了可持久化字典树页面的错误
  docs/ds/code/persistent-trie/persistent-trie_1.cpp
  docs/ds/persistent-trie.md
Labels: Pending review / 等待审核
