Repository OI-wiki/OI-wiki, pull requests merged in 2022-02, with the labels that each got.

#3109 fix: OI-wiki gitment 171
  docs/ds/block-array.md
Labels: Pending review / 等待审核, Easy / 小修小改

#3780 fix(doc): 将 HDU 的部分链接转向其他相同网站
  docs/basic/code/simulate/simulate_1.cpp
  docs/basic/examples/simulate/simulate_1.ans
  docs/basic/examples/simulate/simulate_1.in
  docs/basic/examples/simulate/simulate_2.ans
  docs/basic/examples/simulate/simulate_2.in
  docs/basic/simulate.md
  docs/geometry/scanning.md
  docs/graph/2-sat.md
  docs/math/poly/fft.md
  docs/string/sam.md
Labels: Pending review / 等待审核

#3801 chore(docs): 关于 Python 镜像链接的变化
  docs/lang/python.md
Labels: Pending review / 等待审核

#3795 feat(math/gen-func/symbolic-method.md): add symbolic method
  docs/math/gen-func/symbolic-method.md
  mkdocs.yml
Labels: Pending review / 等待审核

#3723 fix(misc/two-pointer): 修改一些关于复杂度的描述
  docs/misc/two-pointer.md
Labels: Pending review / 等待审核

#3789 feat(test): add skip_test
  scripts/test.py
Labels: Discussion / 需要讨论, 中优先级 / P2

#3765 feat(poly/fft): 应评论需求增加三次转两次代码
  docs/math/code/poly/fft/fft_2.cpp
  docs/math/examples/poly/fft/fft_2.ans
  docs/math/examples/poly/fft/fft_2.in
  docs/math/poly/fft.md
Labels: Pending review / 等待审核

#3817 fix(math/newton.md): remove incorrect description
  docs/math/newton.md
Labels: Pending review / 等待审核
