Repository OI-wiki/OI-wiki, pull requests merged in 2022-08, with the labels that each got.

#4157 feat(basic): add semantic label for paragraph
  docs/basic/binary-lifting.md
  docs/basic/binary.md
  docs/basic/bubble-sort.md
  docs/basic/bucket-sort.md
  docs/basic/complexity.md
  docs/basic/construction.md
  docs/basic/counting-sort.md
  docs/basic/divide-and-conquer.md
  docs/basic/greedy.md
  docs/basic/heap-sort.md
  docs/basic/insertion-sort.md
  docs/basic/merge-sort.md
  docs/basic/prefix-sum.md
  docs/basic/quick-sort.md
  docs/basic/radix-sort.md
  docs/basic/selection-sort.md
  docs/basic/shell-sort.md
  docs/basic/sort-intro.md
  docs/basic/tournament-sort.md
Labels: mergify/can-merge

#4159 fix(/math/number-theory/crt):修改了一些错误
  docs/math/number-theory/crt.md
Labels: mergify/can-merge

#4158 fix(ds/hash): 关于哈希表页面表述的完善
  docs/ds/hash.md
Labels: Pending review / 等待审核

#4165 快速幂词条的翻译
  docs/_redirects
  docs/math/binary-exponentiation.md
  mkdocs.yml
Labels: mergify/can-merge

#4170 fix(dp/opt/slope): typo
  docs/dp/opt/slope.md
Labels: mergify/can-merge

#3228 refactor(lang/python): 大幅修改并增加了 Python 速成 的内容
  docs/lang/python.md
Labels: Pending review / 等待审核, mergify/can-merge

#4168 Revert "ci: building pdfs silently"
  .github/CODEOWNERS
  .github/workflows/build-pdf.yml
Labels: Pending review / 等待审核

#4177 fix(ds/li-chao-tree.md)：修改错误的代码
  docs/ds/code/li-chao-tree/li-chao-tree_1.cpp
  docs/ds/li-chao-tree.md
Labels: mergify/can-merge

#4166 有关渐进分析的解释
  docs/basic/complexity.md
Labels: mergify/can-merge

#4167 feat(ds/rbtree.md): add introduction to rbtree
  docs/ds/avl.md
  docs/ds/code/avl-tree/AvlTreeMap.hpp
  docs/ds/code/rbtree/RBTreeMap.hpp
  docs/ds/images/rbtree-btree-analogy.svg
  docs/ds/images/rbtree-example.svg
  docs/ds/images/rbtree-insert-case4.png
  docs/ds/images/rbtree-insert-case5.png
  docs/ds/images/rbtree-insert-case6.png
  docs/ds/images/rbtree-remove-case1.png
  docs/ds/images/rbtree-remove-case2.png
  docs/ds/images/rbtree-remove-case3.png
  docs/ds/images/rbtree-remove-case4.png
  docs/ds/images/rbtree-remove-case5.png
  docs/ds/images/rbtree-rotations.svg
  docs/ds/rbtree.md
  mkdocs.yml
Labels: mergify/can-merge

#4181 style(lang/python): replace console with pycon for REPL code blocks
  docs/basic/complexity.md
  docs/lang/python.md
  docs/math/complex.md
Labels: mergify/can-merge

#4162 fix(misc/garsia-wachs): 翻译翻译腔句子
  docs/lang/python.md
  docs/misc/garsia-wachs.md
Labels: Pending review / 等待审核, mergify/can-merge

#4136 feat(graph/scc): 完善算法流程,令其可读性更强
  docs/graph/scc.md
  docs/lang/python.md
Labels: mergify/can-merge

#4187 fix(ds/code/binary-heap): typo
  docs/ds/code/binary-heap/binary-heap_1.cpp
Labels: mergify/can-merge

#4194 fix(workflows/build-pdf.yml): lock latex by repo
  .github/workflows/build-pdf.yml
Labels: Pending review / 等待审核, 高优先级 / P1, dependencies, mergify/can-merge

#4192 fix: correct a link
  docs/math/number-theory/pollard-rho.md
Labels: mergify/can-merge

#4038 feat: A format checker guided by format manuals v0.1
  .github/CODEOWNERS
  package.json
  scripts/checker/checker.ts
  scripts/checker/checker_flag.json
  yarn.lock
Labels: Pending review / 等待审核, mergify/can-merge

#4195 fix(intro/docker-deploy, .bashrc, Dockerfile): 解决本地部署服务器时无法使用其他设备访问的问题
  .bashrc
  Dockerfile
  docs/intro/docker-deploy.md
Labels: Pending merge / 等待合并, mergify/can-merge

#4231 fix(math/number-theory/sieve): 修复 Python 代码中错误的自增运算
  docs/math/number-theory/sieve.md
Labels: mergify/can-merge

#4232 feat: 补充离散对数、剩余与单位根的概念
  docs/_redirects
  docs/math/number-theory/discrete-logarithm.md
  docs/math/number-theory/residue.md
  mkdocs.yml
Labels: mergify/can-merge

#4234 Update hash.md
  docs/ds/hash.md
Labels: mergify/can-merge

#4227 feat:add astar-1 config
  docs/search/config/astar/astar_1.yml
Labels: Fix in progress / 正在修锅

#4220 refactor(ds/ett): rewrite ett page
  docs/ds/code/ett/ett_connectivity.cpp
  docs/ds/code/ett/ett_subtree_size.cpp
  docs/ds/ett.md
  docs/ds/examples/ett/ett_connectivity.ans
  docs/ds/examples/ett/ett_connectivity.in
  docs/ds/examples/ett/ett_subtree_size.ans
  docs/ds/examples/ett/ett_subtree_size.in
Labels: Pending review / 等待审核

#3032 feat(3d): add 3d basic
  docs/geometry/3d.md
Labels: Work in Progress / 施工中, Busy Author / 作者正忙

#4255 fix(math/number-theory/gcd.md): 统一称呼
  docs/ds/ett.md
  docs/math/number-theory/gcd.md
Labels: mergify/can-merge

#4260 fix(convex-hull.md): 错误的习题排版与标题嵌套
  docs/geometry/convex-hull.md
Labels: mergify/can-merge
