Repository OI-wiki/OI-wiki, pull requests merged in 2022-09, with the labels that each got.

#4183 feat(ds/b-tree.md): 增加B树讲解
  docs/ds/b-tree.md
  docs/ds/images/b-tree-1.svg
  docs/ds/images/b-tree-2.svg
  docs/ds/images/b-tree-3.svg
  docs/ds/images/b-tree-4.svg
  docs/ds/images/b-tree-5.svg
  docs/ds/images/b-tree-6.svg
  docs/ds/images/b-tree-7.svg
  mkdocs.yml
Labels: Pending review / 等待审核, Format fix needed / 格式需修正, Fix in progress / 正在修锅, Need Processing / 需要处理, Work in Progress / 施工中, Pending apply suggestions / 等待采纳建议, 等待取消修改请求 / Pending Cancel Changes Request, mergify/can-merge

#4237 feat(ds/bplus-tree)：增加B+树讲解
  docs/ds/bplus-tree.md
  docs/ds/images/bplus-tree-1.png
  docs/ds/images/bplus-tree-10.png
  docs/ds/images/bplus-tree-2.webp
  docs/ds/images/bplus-tree-3.webp
  docs/ds/images/bplus-tree-4.webp
  docs/ds/images/bplus-tree-5.webp
  docs/ds/images/bplus-tree-6.webp
  docs/ds/images/bplus-tree-7.png
  docs/ds/images/bplus-tree-8.png
  docs/ds/images/bplus-tree-9.png
  docs/tools/editor/images/npp-lang.gif
  mkdocs.yml
Labels: Pending apply suggestions / 等待采纳建议

#4283 feat:(product.md)：更新了二重外积
  docs/math/linear-algebra/product.md
Labels: mergify/can-merge

#4290 fix&feat: tools/editor/vscode 修改部分标题，补充 clang 有关内容
  docs/tools/editor/images/vscode-9.png
  docs/tools/editor/vscode.md
Labels: mergify/can-merge

#4289 fix(kmp): correct collapse syntax
  docs/string/kmp.md
Labels: mergify/can-merge

#4299 fix(math/coordinate.md): Markdown & LaTeX 修复
  docs/math/coordinate.md
Labels: mergify/can-merge

#4071 fix(ds/code/kdt/kdt_1): 更正kd树代码错误
  docs/ds/code/kdt/kdt_1.cpp
Labels: Pending review / 等待审核

#2968 [refine][sa] 优化文本
  docs/basic/counting-sort.md
  docs/string/basic.md
  docs/string/sa.md
Labels: Discussion / 需要讨论, Pending review / 等待审核

#4304 feat(math): add semantic label for paragraph
  docs/math/balanced-ternary.md
  docs/math/bignum.md
  docs/math/binary-exponentiation.md
  docs/math/combinatorics/combination.md
  docs/math/combinatorics/drawer-principle.md
  docs/math/combinatorics/inclusion-exclusion-principle.md
  docs/math/combinatorics/stirling.md
  docs/math/complex.md
  docs/math/fourier-motzkin-elimination.md
  docs/math/group-theory.md
  docs/math/linear-algebra/basis.md
  docs/math/linear-algebra/char-poly.md
  docs/math/linear-algebra/gauss.md
  docs/math/newton.md
  docs/math/number-theory/bezouts.md
  docs/math/number-theory/crt.md
  docs/math/number-theory/discrete-logarithm.md
  docs/math/number-theory/euclidean.md
  docs/math/number-theory/euler.md
  docs/math/number-theory/fermat.md
  docs/math/number-theory/gcd.md
  docs/math/number-theory/inverse.md
  docs/math/number-theory/lagrange.md
  docs/math/number-theory/lift-the-exponent.md
  docs/math/number-theory/linear-equation.md
  docs/math/number-theory/lucas.md
  docs/math/number-theory/min-25.md
  docs/math/number-theory/mobius.md
  docs/math/number-theory/pollard-rho.md
  docs/math/number-theory/powerful-number.md
  docs/math/number-theory/prime.md
  docs/math/number-theory/quad-residue.md
  docs/math/number-theory/quadratic.md
  docs/math/number-theory/residue.md
  docs/math/number-theory/sieve.md
  docs/math/number-theory/sqrt-decomposition.md
  docs/math/number-theory/stern-brocot.md
  docs/math/number-theory/wilson.md
  docs/math/number-theory/zhou.md
  docs/math/order-theory.md
  docs/math/permutation-group.md
  docs/math/poly/fundamental.md
  docs/math/schreier-sims.md
  docs/math/simplex.md
  docs/math/young-tableau.md
Labels: mergify/can-merge

#4302 refactor(vector.md, vector-space.md, basis.md): 线性空间和线性基
  docs/math/code/basis/basis_1.cpp
  docs/math/code/basis/basis_2.cpp
  docs/math/examples/basis/basis_1.ans
  docs/math/examples/basis/basis_1.in
  docs/math/examples/basis/basis_2.ans
  docs/math/examples/basis/basis_2.in
  docs/math/linear-algebra/basis.md
  docs/math/linear-algebra/images/basis1.png
  docs/math/linear-algebra/images/basis2.png
  docs/math/linear-algebra/images/basis3.png
  docs/math/linear-algebra/images/basis4.png
  docs/math/linear-algebra/images/misc1.png
  docs/math/linear-algebra/vector-space.md
  docs/math/linear-algebra/vector.md
  mkdocs.yml
Labels: mergify/can-merge

#4312 fix(math/number-theory/gcd, euler, sieve, stern-brocot, lagrange): style fix
  docs/math/number-theory/euler.md
  docs/math/number-theory/gcd.md
  docs/math/number-theory/lagrange.md
  docs/math/number-theory/sieve.md
  docs/math/number-theory/stern-brocot.md
Labels: mergify/can-merge

#4306 feat(math/notation): 增加更多常用符号
  docs/math/linear-algebra/vector.md
  docs/math/notation.md
Labels: mergify/can-merge

#4316 fix(ac-automaton): 修正一个格式语法错误
  docs/string/ac-automaton.md
Labels: mergify/can-merge

#4318 fix(intro/htc.md): incorrect modification in #3055
  docs/intro/htc.md
Labels: mergify/can-merge

#4300 feat(dsu): 添加删除操作 & 重构其他部分
  docs/ds/dsu.md
Labels: mergify/can-merge

#4323 fix: internal links
  docs/dp/dynamic.md
  docs/dp/probability.md
  docs/ds/b-tree.md
  docs/ds/bplus-tree.md
  docs/ds/treap.md
  docs/geometry/2d.md
  docs/graph/lgv.md
  docs/lang/python.md
  docs/math/binary-exponentiation.md
  docs/math/complex.md
  docs/math/linear-algebra/basis.md
  docs/math/linear-algebra/gauss.md
  docs/math/linear-algebra/matrix.md
  docs/math/linear-recurrence.md
  docs/math/number-theory/gcd.md
  docs/math/number-theory/pell-equation.md
  docs/math/poly/lagrange.md
  docs/misc/cdq-divide.md
  docs/tools/editor/images/npp-lang.gif
Labels: mergify/can-merge

#4281 feat:(expression.md)：完善表达式求值
  docs/misc/expression.md
Labels: mergify/can-merge

#4317 Update:(vector-space.md)：线性代数框架搭建3
  docs/math/linear-algebra/vector-space.md
Labels: mergify/can-merge

#4326 feat:add ds config
  docs/ds/config/binary-heap/binary-heap_1.yml
  docs/ds/config/block-list/block-list_1.yml
  docs/ds/config/cartesian-tree/cartesian-tree_1.yml
  docs/ds/config/decompose/decompose_1.yml
  docs/ds/config/dividing/dividing_1.yml
  docs/ds/config/ett/ett_1.yml
  docs/ds/config/ett/ett_connectivity.yml
  docs/ds/config/ett/ett_subtree_size.yml
  docs/ds/config/kdt/kdt_1.yml
  docs/ds/config/kdt/kdt_2.yml
  docs/ds/config/kdt/kdt_3.yml
  docs/ds/config/leftist-tree/leftist-tree_1.yml
  docs/ds/config/leftist-tree/leftist-tree_2.yml
  docs/ds/config/leftist-tree/leftist-tree_3.yml
  docs/ds/config/li-chao-tree/li-chao-tree_1.yml
  docs/ds/config/monotonous-queue/monotonous-queue_1.yml
  docs/ds/config/monotonous-queue/monotonous-queue_2.yml
  docs/ds/config/persistent-seg/persistent-seg_1.yml
  docs/ds/config/persistent-trie/persistent-trie_1.yml
  docs/ds/config/queue/queue_1.yml
  docs/ds/config/seg-beats/seg-beats_1.yml
  docs/ds/config/seg-beats/seg-beats_2.yml
  docs/ds/config/seg-beats/seg-beats_3.yml
  docs/ds/config/seg/seg_1.yml
  docs/ds/config/seg/seg_2.yml
  docs/ds/config/seg/seg_3.yml
  docs/ds/config/sparse-table/sparse-table_1.yml
  docs/ds/config/treap/treap_1.yml
  docs/ds/config/tree-decompose/tree-decompose_1.yml
Labels: Pending review / 等待审核, Need Processing / 需要处理

#4327 feat:add geometry config
  docs/geometry/config/3d/3d_1.yml
  docs/geometry/config/pick/pick_1.yml
Labels: Pending review / 等待审核, Need Processing / 需要处理, mergify/can-merge

#4328 feat:add graph config
  docs/graph/config/2-sat/2-sat_1.yml
  docs/graph/config/2-sat/2-sat_2.yml
  docs/graph/config/bfs/bfs_1.yml
  docs/graph/config/block-forest/block-forest_1.yml
  docs/graph/config/block-forest/block-forest_2.yml
  docs/graph/config/block-forest/block-forest_3.yml
  docs/graph/config/cut/cut_1.yml
  docs/graph/config/diff-constraints/diff-constraints_1.yml
  docs/graph/config/dynamic-tree-divide/dynamic-tree-divide_1.yml
  docs/graph/config/dynamic-tree-divide/dynamic-tree-divide_2.yml
  docs/graph/config/euler/euler_1.yml
  docs/graph/config/hld/hld_1.yml
  docs/graph/config/hld/hld_3.yml
  docs/graph/config/lca/lca_2.yml
  docs/graph/config/lgv/lgv_1.yml
  docs/graph/config/lgv/lgv_2.yml
  docs/graph/config/max-clique/max-clique_1.yml
  docs/graph/config/max-clique/max-clique_2.yml
  docs/graph/config/mod-shortest-path/mod-shortest-path_1.yml
  docs/graph/config/mst/mst_1.yml
  docs/graph/config/mst/mst_2.yml
  docs/graph/config/steiner-tree/steiner-tree_1.yml
  docs/graph/config/steiner-tree/steiner-tree_2.yml
  docs/graph/config/stoer-wagner/stoer-wagner_1.yml
  docs/graph/config/tree-ahu/tree-ahu_1.yml
  docs/graph/config/tree-divide/tree-divide_1.yml
  docs/graph/config/tree-divide/tree-divide_2.yml
  docs/graph/config/tree-divide/tree-divide_3.yml
  docs/graph/config/tree-hash/tree-hash_1.yml
  docs/graph/config/tree-hash/tree-hash_2.yml
  docs/graph/config/tree-hash/tree-hash_3.yml
Labels: Pending review / 等待审核, Need Processing / 需要处理

#4329 feat:add math config
  docs/math/config/du/du_1.yml
  docs/math/config/du/du_2.yml
  docs/math/config/inclusion-exclusion-principle/inclusion-exclusion-principle_1.yml
  docs/math/config/min-25/min-25_1.yml
  docs/math/config/mobius/mobius_1.yml
  docs/math/config/mobius/mobius_2.yml
  docs/math/config/mobius/mobius_3.yml
  docs/math/config/mobius/mobius_4.yml
  docs/math/config/mobius/mobius_5.yml
  docs/math/config/pollard-rho/pollard-rho_1.yml
  docs/math/config/poly/fft/fft_1.yml
  docs/math/config/poly/fft/fft_2.yml
  docs/math/config/poly/fft/fft_3.yml
  docs/math/config/poly/lagrange/lagrange_1.yml
  docs/math/config/poly/lagrange/lagrange_2.yml
  docs/math/config/poly/sqrt/sqrt_1.yml
  docs/math/config/powerful-number/powerful-number_1.yml
  docs/math/config/powerful-number/powerful-number_2.yml
  docs/math/config/prime/prime_1.yml
  docs/math/config/prime/prime_2.yml
  docs/math/config/quick-pow/quick-pow_1.yml
  docs/math/config/simplex/simplex_1.yml
  docs/math/config/wilson/wilson_1.yml
Labels: Pending review / 等待审核, Need Processing / 需要处理

#4330 feat:add misc config
  docs/misc/config/cdq-divide/cdq-divide_1.yml
  docs/misc/config/cdq-divide/cdq-divide_2.yml
  docs/misc/config/cdq-divide/cdq-divide_3.yml
  docs/misc/config/cdq-divide/cdq-divide_4.yml
  docs/misc/config/hill-climbing/hill-climbing_1.yml
  docs/misc/config/hill-climbing/hill-climbing_2.yml
  docs/misc/config/hoverline/hoverline_1.yml
  docs/misc/config/hoverline/hoverline_2.yml
  docs/misc/config/hoverline/hoverline_3.yml
  docs/misc/config/mo-algo-with-bitset/mo-algo-with-bitset_1.yml
  docs/misc/config/mo-algo/mo-algo_1.yml
  docs/misc/config/modifiable-mo-algo/modifiable-mo-algo_1.yml
  docs/misc/config/parallel-binsearch/parallel-binsearch_1.yml
  docs/misc/config/rollback-mo-algo/rollback-mo-algo_1.yml
  docs/misc/config/simulated-annealing/simulated-annealing_1.yml
Labels: Pending review / 等待审核, Need Processing / 需要处理

#4332 feat:add basic config
  docs/basic/config/binary/binary_1.yml
  docs/basic/config/greedy/greedy_1.yml
  docs/basic/config/prefix-sum/prefix-sum_1.yml
  docs/basic/config/prefix-sum/prefix-sum_2.yml
  docs/basic/config/prefix-sum/prefix-sum_3.yml
  docs/basic/config/simulate/simulate_1.yml
Labels: Pending review / 等待审核, Need Processing / 需要处理

#4331 feat:add string config
  docs/string/config/ac-automaton/ac-automaton_1.yml
  docs/string/config/ac-automaton/ac-automaton_2.yml
  docs/string/config/general-sam/general-sam_1.yml
  docs/string/config/general-sam/general-sam_2.yml
  docs/string/config/hash/hash_1.yml
  docs/string/config/pam/pam_1.yml
  docs/string/config/pam/pam_2.yml
  docs/string/config/sa/sa_1.yml
  docs/string/config/sa/sa_2.yml
  docs/string/config/sa/sa_3.yml
  docs/string/config/seq-automaton/seq-automaton_1.yml
  docs/string/config/suffix-bst/suffix-bst_1.yml
  docs/string/config/suffix-bst/suffix-bst_2.yml
  docs/string/config/trie/trie_1.yml
  docs/string/config/trie/trie_2.yml
  docs/string/config/trie/trie_3.yml
Labels: Pending review / 等待审核, Need Processing / 需要处理

#4325 feat:add dp config
  docs/dp/config/dag/dag_1.yml
  docs/dp/config/dynamic/dynamic_1.yml
  docs/dp/config/knapsack/knapsack_1.yml
  docs/dp/config/knapsack/knapsack_2.yml
  docs/dp/config/opt/monotonous-queue-stack/monotonous-queue-stack_1.yml
  docs/dp/config/plug/plug_1.yml
  docs/dp/config/plug/plug_2.yml
  docs/dp/config/plug/plug_3.yml
  docs/dp/config/plug/plug_4.yml
  docs/dp/config/probability/probability_1.yml
  docs/dp/config/probability/probability_2.yml
  docs/dp/config/probability/probability_3.yml
  docs/dp/config/state/state_1.yml
  docs/dp/config/tree/tree_1.yml
  docs/dp/config/tree/tree_2.yml
  docs/dp/config/tree/tree_3.yml
Labels: Pending review / 等待审核, Need Processing / 需要处理, mergify/can-merge

#4339 fix(lang/class.md): 修复求向量内积的代码错误 (#4338)
  docs/lang/class.md
Labels: mergify/can-merge

#4274 feat(graph/graph-matching/bigraph-match): 继承前人的二分图最大匹配加入描述
  docs/graph/graph-matching/bigraph-match.md
Labels: mergify/can-merge

#4345 fix(docs/math/number-theory/sieve.md): 修复莫比乌斯函数实现的代码缩进问题
  docs/math/number-theory/sieve.md
Labels: mergify/can-merge

#4342 feat(ds, graph): add semantic label for paragraph
  docs/ds/avl.md
  docs/ds/b-tree.md
  docs/ds/balanced-in-seg.md
  docs/ds/binary-heap.md
  docs/ds/block-array.md
  docs/ds/block-list.md
  docs/ds/bplus-tree.md
  docs/ds/bst.md
  docs/ds/cartesian-tree.md
  docs/ds/dividing.md
  docs/ds/dsu-complexity.md
  docs/ds/dsu.md
  docs/ds/fenwick.md
  docs/ds/hash.md
  docs/ds/leftist-tree.md
  docs/ds/li-chao-tree.md
  docs/ds/linked-list.md
  docs/ds/llrbt.md
  docs/ds/monotonous-queue.md
  docs/ds/monotonous-stack.md
  docs/ds/pairing-heap.md
  docs/ds/persistent-heap.md
  docs/ds/persistent-seg.md
  docs/ds/persistent-trie.md
  docs/ds/queue.md
  docs/ds/rbtree.md
  docs/ds/seg-in-seg.md
  docs/ds/seg.md
  docs/ds/sgt.md
  docs/ds/sparse-table.md
  docs/ds/splay.md
  docs/ds/sqrt-tree.md
  docs/ds/stack.md
  docs/ds/wblt.md
  docs/graph/bcc.md
  docs/graph/block-forest.md
  docs/graph/color.md
  docs/graph/cut.md
  docs/graph/dfs.md
  docs/graph/diff-constraints.md
  docs/graph/dmst.md
  docs/graph/dsu-on-tree.md
  docs/graph/euler.md
  docs/graph/flow/max-flow.md
  docs/graph/graph-matching/augment.md
  docs/graph/graph-matching/bigraph-match.md
  docs/graph/kth-path.md
  docs/graph/lca.md
  docs/graph/max-clique.md
  docs/graph/mdst.md
  docs/graph/min-circle.md
  docs/graph/prufer.md
  docs/graph/scc.md
  docs/graph/shortest-path.md
  docs/graph/stoer-wagner.md
  docs/graph/topo.md
  docs/graph/tree-ahu.md
  docs/graph/tree-basic.md
  docs/graph/tree-diameter.md
  docs/graph/virtual-tree.md
Labels: mergify/can-merge

#4349 feat(dsu): 添加移动操作 & 添加例题 & 修正部分错误 & 重构部分代码
  docs/ds/code/dsu/dsu_1.cpp
  docs/ds/code/dsu/dsu_1.py
  docs/ds/dsu.md
  docs/ds/examples/dsu/dsu_1.ans
  docs/ds/examples/dsu/dsu_1.in
Labels: mergify/can-merge

#4347 feat(ds/sbt): add size balanced tree
  docs/ds/code/size-balanced-tree/SizeBalancedTreeMap.hpp
  docs/ds/sbt.md
Labels: mergify/can-merge

#3733 feat(ds/splay): time complexity analysis
  docs/ds/images/splay-zig-zag.svg
  docs/ds/images/splay-zig-zag.tex
  docs/ds/images/splay-zig-zig.svg
  docs/ds/images/splay-zig-zig.tex
  docs/ds/images/splay-zig.svg
  docs/ds/images/splay-zig.tex
  docs/ds/splay.md
  mkdocs.yml
Labels: Pending apply suggestions / 等待采纳建议, Busy Author / 作者正忙, mergify/can-merge

#4355 update(permulaton.md)：增加置换和排列
  docs/math/permulation.md
  docs/math/permutation-group.md
  mkdocs.yml
Labels: mergify/can-merge

#4357 fix(string/trie.md): python 版本实例 trie 代码
  docs/string/trie.md
Labels: mergify/can-merge

#4361 feat(tree-random-walk): create tree-random-walk
  docs/graph/tree-random-walk.md
  mkdocs.yml
Labels: mergify/can-merge

#4354 feat(concentration-inequality.md): 添加概率不等式相关内容
  docs/_redirects
  docs/dp/probability.md
  docs/math/expectation.md
  docs/math/probability/basic-conception.md
  docs/math/probability/concentration-inequality.md
  docs/math/probability/conditional-probability.md
  docs/math/probability/exp-var.md
  docs/math/probability/random-variable.md
  docs/misc/rand-technique.md
  mkdocs.yml
Labels: mergify/can-merge
