Repository OI-wiki/OI-wiki, pull requests merged in 2022-07, with the labels that each got.

#4010 refactor(dp/plug): 调整标题层次，完善习题题意
  docs/dp/plug.md
Labels: Pending review / 等待审核

#4048 refactor(geometry/3d), feat(geometry/convex-hull): move convex
  docs/geometry/3d.md
  docs/geometry/convex-hull.md
Labels: Pending review / 等待审核

#3919 更新了代数基本定理
  docs/math/poly/fundamental.md
  mkdocs.yml
Labels: Pending review / 等待审核

#3917 feat: 更新了Stern-Brocot树、Farey序列与Pell方程相关内容
  docs/math/number-theory/continued-fraction.md
  docs/math/number-theory/pell-equation.md
  docs/math/number-theory/stern-brocot.md
Labels: Pending review / 等待审核

#4045 refactor(basic/binary.md): 对“三分法”部分进行整体修改(#4002 ,#4039 )
  docs/basic/binary.md
  docs/basic/code/binary/binary_1.cpp
  docs/basic/examples/binary/binary_1.ans
  docs/basic/examples/binary/binary_1.in
  docs/basic/images/binary1.svg
  docs/basic/images/binary2.svg
Labels: Pending review / 等待审核

#4051 feat(josephus.md)对递推式补充解释(正确版)
  docs/misc/josephus.md
Labels: Pending review / 等待审核

#4054 fix(binary.md): 修改公式中常量的字体；修正错误的公式格式；修改内容表述；增加例题
  docs/basic/binary.md
Labels: Pending review / 等待审核

#4053 fix(basic/complexity): 更正主定理证明的格式
  docs/basic/complexity.md
  docs/basic/images/master-theorem-proof.svg
Labels: Pending review / 等待审核

#3930 feat&refactor(poly/fft): 继承前人的pr试着修改了一下FFT页面
  docs/math/code/poly/fft/fft_3.cpp
  docs/math/examples/poly/fft/fft_3.ans
  docs/math/examples/poly/fft/fft_3.in
  docs/math/poly/fft.md
Labels: Pending review / 等待审核, Fix in progress / 正在修锅, Pending merge / 等待合并, Work in Progress / 施工中, Awaiting Review / PR 待合

#4078 fix(mkdocs.yml): Change title of cpp-other-langs to "C++ 与其他常用语言的区别"
  mkdocs.yml
Labels: Pending merge / 等待合并, Awaiting Review / PR 待合

#4087 ci: fix celebration by adding requests to Pipfile
  Pipfile
  Pipfile.lock
Labels: mergify/can-merge

#4077 fix(math/number-theory/basic.md): 不可约数是质数的整环示例
  docs/math/number-theory/basic.md
Labels: Pending review / 等待审核, Awaiting Review / PR 待合, mergify/can-merge

#4088 fix: remove rubbish span tag
  docs/contest/problems.md
  docs/lang/csl/associative-container.md
  docs/lang/op-overload.md
  docs/lang/var.md
  docs/math/poly/intro.md
  docs/math/poly/newton.md
Labels: mergify/can-merge

#4091 fix(ds/seg): 优化代码结构，使上下文一致，提高阅读体验
  docs/ds/seg.md
Labels: Pending review / 等待审核, mergify/can-merge

#4093 fix(basic/complexity): latex <= -> \leq
  docs/basic/complexity.md
Labels: mergify/can-merge

#4085 chore: rename LaTeX workflow
  .github/workflows/build-pdf.yml
Labels: mergify/can-merge

#4092 feat(dp/basic): 加入最长公共子序列的名词解释和例题
  docs/dp/basic.md
Labels: Pending review / 等待审核, mergify/can-merge

#4109 fix(ds/segt4.svg): 解决 Windows 上 Microsoft Edge 显示图片异常的问题（部分数字不在框内）
  docs/ds/images/segt4.svg
Labels: Pending review / 等待审核, mergify/can-merge

#4127 写清楚适配器的底层容器对象
  docs/lang/csl/container.md
Labels: Pending review / 等待审核, mergify/can-merge

#4128 fix(ds/queue): 修正一处笔误
  docs/ds/queue.md
Labels: mergify/can-merge

#3958 feat&refactor(number-theory/quadratic): 更新了二次域相关内容
  docs/math/number-theory/continued-fraction.md
  docs/math/number-theory/images/quadratic.png
  docs/math/number-theory/quadratic.md
  mkdocs.yml
Labels: Pending review / 等待审核, mergify/can-merge

#3903 feat(math/probability): 完善概率论相关理论的讨论
  docs/math/expectation.md
  docs/math/probability/basic-conception.md
  docs/math/probability/conditional-probability.md
  docs/math/probability/exp-var.md
  docs/math/probability/random-variable.md
  mkdocs.yml
Labels: Pending review / 等待审核, mergify/can-merge

#4120 feat(math/linear-algebra-index.md): 添加线性代数简介与线性空间相关内容
  docs/math/linear-algebra-index.md
  docs/math/vector.md
  mkdocs.yml
Labels: Pending review / 等待审核, mergify/can-merge

#4141 feat(ds/avl.md): add code example for avltree
  docs/ds/avl.md
Labels: mergify/can-merge

#4052 ci: building pdfs silently
  .github/CODEOWNERS
  .github/workflows/build-pdf.yml
Labels: Pending review / 等待审核, Pending merge / 等待合并, Awaiting Review / PR 待合, mergify/can-merge

#4063 fix(math/notation): \frac -> \dfrac
  docs/math/notation.md
Labels: mergify/can-merge

#4149 ci(Mergify): defer to merge when require other PR
  .mergify.yml
Labels: mergify/can-merge

#3875 fix(math/vector): more formal
  docs/math/vector.md
Labels: Discussion / 需要讨论, No Response / 失去响应

#4113 feat(ds/block-list): 新增 __gnu_cxx::rope
  docs/ds/block-list.md
Labels: Pending review / 等待审核, mergify/can-merge

#4139 feat(graph/mod-shortest-path): 补充描述
  docs/graph/mod-shortest-path.md
Labels: mergify/can-merge
