Repository OI-wiki/OI-wiki, pull requests merged in 2022-03, with the labels that each got.

#3770 fix(graph/steiner-tree.md): fix typo
  docs/graph/steiner-tree.md
Labels: Pending review / 等待审核

#3842 feat(math/berlekamp-massey.md): 添加 Berlekamp-Massey 算法页面
  docs/math/berlekamp-massey.md
  mkdocs.yml
Labels: Pending review / 等待审核

#3843 fix(script/BaiduPusher): try to fix by remove useless `source /etc/profile`
  scripts/BaiduPusher.sh
Labels: Pending review / 等待审核

#3856 feat(c-cpp): bool type is not supported in ANSI C
  docs/lang/c-cpp.md
Labels: Pending review / 等待审核

#3846 fix(shortest-path): fix cpp code of bellman-ford algorithm
  docs/graph/shortest-path.md
Labels: Pending review / 等待审核

#3847 feat(math/number-theory/sieve): add 一般积性函数的线性筛
  docs/math/number-theory/sieve.md
Labels: Pending review / 等待审核

#3868 fix(string/match): Fix condition
  docs/string/match.md
Labels: Pending review / 等待审核

#3878 fix(problemsetting.md): use `std::shuffle`
  docs/contest/problemsetting.md
Labels: Pending review / 等待审核

#3805 fix(ds/pq-tree): 更正了时间复杂度
  docs/ds/pq-tree.md
Labels: Pending review / 等待审核

#3824 feat(math/bit): 添加汉明权重 (#3793)
  docs/math/bit.md
Labels: More details needed / 内容需增修, Pending apply suggestions / 等待采纳建议

#3887 fix(simplex): fix format
  docs/math/simplex.md
Labels: Pending review / 等待审核

#3886 fix(inclusion-exclusion-principle.md): 修复符号错误
  docs/math/combinatorics/inclusion-exclusion-principle.md
Labels: Pending review / 等待审核

#3849 fix(ds/fenwick): 修改了 取反符号~ 无法正确显示的问题
  docs/ds/fenwick.md
Labels: Pending apply suggestions / 等待采纳建议
