Repository OI-wiki/OI-wiki, pull requests merged in 2023-12, with the labels that each got.

#5294 fix(math/catalan.md): Catalan 数应用描述修正
  docs/math/combinatorics/catalan.md
Labels: Pending apply suggestions / 等待采纳建议

#5272 fix(graph/mst): 修正了 NOI 2018 归程做法的笔误
  docs/graph/mst.md
Labels: No Response / 失去响应

#5330 ci(typst): remove texmath
  .github/workflows/build-pdf-typst.yml
Labels: mergify/can-merge
