Repository OI-wiki/OI-wiki, pull requests merged in 2023-01, with the labels that each got.

#4560 refactor: remove deprecated use of the `register` keyword
  docs/contest/io.md
  docs/ds/code/leafy-tree/leafy-tree_1.cpp
  docs/ds/code/seg-beats/seg-beats_2.cpp
  docs/graph/code/tree-divide/tree-divide_3.cpp
  docs/graph/code/tree-hash/tree-hash_2.cpp
  docs/math/poly/ntt.md
  docs/misc/mo-algo-on-tree.md
  docs/search/code/dlx/dlx_1.cpp
  docs/search/code/dlx/dlx_2.cpp
  docs/search/code/dlx/dlx_4.cpp
Labels: mergify/can-merge

#4573 refactor: 用 `aligned` 替换数学公式中的 `split`, `eqnarray` 环境
  docs/ds/sqrt-tree.md
  docs/math/combinatorics/derangement.md
  docs/math/combinatorics/inclusion-exclusion-principle.md
  docs/math/number-theory/du.md
  docs/math/number-theory/euclidean.md
  docs/math/number-theory/wilson.md
  docs/misc/job-order.md
Labels: mergify/can-merge

#4576 fix(integral.md)：修正上文 A,B,C 下文 a,b,c 的小问题
  docs/math/integral.md
Labels: mergify/can-merge

#4529 fix(ds/fenwick): 修改了树状数组部分的内容，修正了文中的配图(#4526)
  docs/ds/fenwick.md
  docs/ds/images/fenwick-query.svg
  docs/ds/images/fenwick-query.tex
  docs/ds/images/fenwick.svg
  docs/ds/images/fenwick.tex
Labels: mergify/can-merge

#4634 fix(math/number-theory/basic.md): 显然约数 -> 平凡约数
  docs/math/number-theory/basic.md
Labels: Pending review / 等待审核

#4457 feat(quick-sort): add median of medians algorithm
  docs/basic/quick-sort.md
Labels: Pending merge / 等待合并
