Repository OI-wiki/OI-wiki, pull requests merged in 2024-07, with the labels that each got.

#5729 feat: 代码片段测试功能实现
  .github/workflows/test.yml
  scripts/test.py
Labels: mergify/can-merge

#5727 feat(sqrt-tree.md): 增加树高的证明
  docs/ds/sqrt-tree.md
Labels: Pending review / 等待审核

#5728 feat(graph/scc): 完善了 Tarjan 算法的引入与前置的栈定义
  docs/graph/scc.md
Labels: Pending apply suggestions / 等待采纳建议

#5734 fix(ds/cartesian-tree.md): fix typo
  docs/ds/cartesian-tree.md
Labels: Pending review / 等待审核

#5662 refact(graph/bcc.md): 修缮内容 (#5661)
  docs/graph/bcc.md
  docs/graph/code/bcc/bcc_1.cpp
  docs/graph/code/bcc/bcc_2.cpp
  docs/graph/code/bcc/bcc_3.cpp
  docs/graph/code/bcc/bcc_4.cpp
  docs/graph/examples/bcc/bcc_1.ans
  docs/graph/examples/bcc/bcc_1.in
  docs/graph/examples/bcc/bcc_2.ans
  docs/graph/examples/bcc/bcc_2.in
  docs/graph/examples/bcc/bcc_3.ans
  docs/graph/examples/bcc/bcc_3.in
  docs/graph/examples/bcc/bcc_4.ans
  docs/graph/examples/bcc/bcc_4.in
Labels: Pending apply suggestions / 等待采纳建议
