Repository OI-wiki/OI-wiki, pull requests merged in 2024-08, with the labels that each got.

#5720 fix(ds/top-tree): misc format fix
  docs/ds/code/top-tree/top-tree_1.cpp
  docs/ds/code/top-tree/top-tree_2.cpp
  docs/ds/config/top-tree/top-tree_1.yml
  docs/ds/config/top-tree/top-tree_2.yml
  docs/ds/examples/top-tree/top-tree_1.ans
  docs/ds/examples/top-tree/top-tree_1.in
  docs/ds/examples/top-tree/top-tree_2.ans
  docs/ds/examples/top-tree/top-tree_2.in
  docs/ds/top-tree.md
Labels: Pending merge / 等待合并

#5752 fix(graph/shortest-path): fix typo
  docs/graph/shortest-path.md
Labels: Pending review / 等待审核

#5760 fix(graph/dominator-tree): 修正支配树的 dag 求法
  docs/graph/dominator-tree.md
Labels: Pending apply suggestions / 等待采纳建议

#5718 fix(docs/ds/avl.md): 规范伪代码
  docs/ds/avl.md
Labels: Pending review / 等待审核

#5741 feat(ds/loser-tree.md): 增加败者树的描述 (Closes #4857)
  docs/ds/code/loser-tree/loser-tree_1.cpp
  docs/ds/config/loser-tree/loser-tree_1.yml
  docs/ds/examples/loser-tree/loser-tree_1.ans
  docs/ds/examples/loser-tree/loser-tree_1.in
  docs/ds/images/loser-tree-1.png
  docs/ds/images/loser-tree-2.apng
  docs/ds/loser-tree.md
  mkdocs.yml
Labels: Pending apply suggestions / 等待采纳建议

#5759 refactor(misc/odt.md): 重写珂朵莉树页面
  docs/misc/odt.md
Labels: Pending review / 等待审核
